### ISSUE TITLE
node 16.14.x support

### ISSUE THREAD

**Issue by fairbairn** [urbdyn/nexe_builds#33]
Would be great if this could be supported, even 16.15 if easier.

**Comment by code-ape** [comment]
@fairbairn Thanks for opening this issue! I just opened up a PR for `16.19.0`. Will that work or do you need 16.15.x specifically?

Referenced PR: #37

**Comment by fairbairn** [comment]
I'm sure that would be fine, that's the latest LTS for v16.

**Comment by code-ape** [comment]
Hey @fairbairn CD build for `16.19.0` just finished if you want to try it out and report if you have any issues :)

GitHub Actions run for CD: https://github.com/urbdyn/nexe_builds/actions/runs/4137792503

**Comment by code-ape** [comment]
Closing for now. @fairbairn let me know if you have any issues related to this in the near future and I can reopen. Thanks!
