### ISSUE TITLE
Release 0.3.0

### ISSUE THREAD

**Issue by code-ape** [urbdyn/nexe_builds#41]
This ticket is to track release of version 0.3.0. This version will build with Nexe `4.0.0-rc.2`.

**Comment by code-ape** [comment]
Release 0.3.0 has been complete! Please update your Nexe remote URL to `https://github.com/urbdyn/nexe_builds/releases/download/0.3.0/`.

CC'ing known users who have opened tickets in the past: @calebboyd, @fairbairn, @SDAdham, @Kampflaus

Please comment below if you encounter any issues with this new release. Thanks 😄

**Comment by SDAdham** [comment]
@code-ape , thank you so much for this. Is it possible u can include x86 builds?

**Comment by code-ape** [comment]
@SDAdham we currently only do `x86_64` builds and currently don't have a way to do `i386` (i.e. `x86_32`) builds on Github Actions. I assume by `x86` you're referring to `x86_64` as that's what most any modern Intel or AMD CPU has been for over a decade now?

Reference to current builds: https://github.com/urbdyn/nexe_builds/releases/tag/0.3.0

**Comment by code-ape** [comment]
Closing for now. Let me know if you have any issues and we can re-open!
